# Generated by Django 3.2.7 on 2021-12-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('BODEGA', 'BODEGA'), ('FINANZAS', 'FINANZAS'), ('COCINA', 'COCINA'), ('TOTEM', 'TOTEM')], default='ADMIN', max_length=30),
        ),
    ]
