# Generated by Django 3.2.7 on 2021-10-27 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orderproduct',
            fields=[
                ('orderproductid', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateField()),
                ('orderhour', models.DateField()),
                ('receptiondate', models.DateField(blank=True, null=True)),
                ('receptionhour', models.DateField(blank=True, null=True)),
                ('totalorderproduct', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Orderproduct',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('idprovider', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
                ('companyname', models.CharField(max_length=30)),
                ('name1', models.CharField(max_length=30)),
                ('name2', models.CharField(max_length=30)),
                ('lastname1', models.CharField(max_length=30)),
                ('lastname2', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=50)),
                ('commune', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=70)),
                ('cellphone', models.IntegerField()),
                ('mail', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Provider',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('purchaseprice', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('criticalstock', models.IntegerField()),
                ('productname', models.CharField(max_length=30)),
                ('productdescription', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=1)),
                ('p_idprovider', models.ForeignKey(db_column='p_idprovider', on_delete=django.db.models.deletion.CASCADE, to='BodegaApp.provider')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Orderproductdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.BigIntegerField()),
                ('opdorderproductid', models.ForeignKey(db_column='opdorderproductid', on_delete=django.db.models.deletion.CASCADE, to='BodegaApp.orderproduct')),
                ('opdproductid', models.ForeignKey(db_column='opdproductid', on_delete=django.db.models.deletion.CASCADE, to='BodegaApp.product')),
            ],
            options={
                'db_table': 'Orderproductdetails',
                'unique_together': {('opdproductid', 'opdorderproductid')},
            },
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='products',
            field=models.ManyToManyField(through='BodegaApp.Orderproductdetails', to='BodegaApp.Product'),
        ),
    ]
